version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - TZ="Asia/Tokyo"
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    #command: "tail -f /dev/null"
    volumes:
      - .:/myapp
      - /myapp/public/
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - LIFF_ID=${LIFF_ID}
      - LINE_LOGIN_CHANNEL_ID=${LINE_LOGIN_CHANNEL_ID}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - LINE_CHANNEL_TOKEN=${LINE_CHANNEL_TOKEN}
      - RAILS_HOST=${RAILS_HOST}
    ports:
      - "3000:3000"
      # for development
      - "8888:8888"
    depends_on:
      - db
volumes:
  pgdata:
